name: Automated Contract Deployment and Interaction

on:
  push:
    branches:
      - debug

jobs:
  deploy_and_interact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.2  # Choose your desired Node.js version

      - name: Load environment variables from .env
        run: |
          cp .env .env.local
          echo "::add-mask::$(< .env.local)"
        shell: bash

      - name: Set CONTRACT_TYPE
        run: |
          if [[ -z "$CONTRACT_TYPE" ]]; then
            echo "CONTRACT_TYPE is not set. Defaulting to ERC20."
            export CONTRACT_TYPE="ERC20"
          fi
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Deploy contract
        id: deployment
        run: |
          if [[ "$CONTRACT_TYPE" == "ERC20" ]]; then
            echo "Debug: Deploying ERC20 contract"
            npx hardhat run scripts/deploy.js --network TESTNET
          elif [[ "$CONTRACT_TYPE" == "ERC721" ]]; then
            echo "Debug: Deploying ERC721 contract"
            npx hardhat run scripts/deploy-nft.js --network TESTNET
          elif [[ "$CONTRACT_TYPE" == "ERC1155" ]]; then
            echo "Debug: Deploying ERC1155 contract"
            npx hardhat run scripts/deploy-erc1155.js --network TESTNET
          else
            echo "Invalid CONTRACT_TYPE: $CONTRACT_TYPE"
            exit 1
          fi
        env:
          CONTRACT_TYPE: ${{ env.CONTRACT_TYPE }}

      - name: Store deployed contract address
        run: |
          NEW_CONTRACT_ADDRESS=$(cat contract-info.json | jq -r '.address')
          echo "CONTRACT_ADDRESS=$NEW_CONTRACT_ADDRESS" >> .env.local
          echo "::add-mask::CONTRACT_ADDRESS=$NEW_CONTRACT_ADDRESS"
        shell: bash

      - name: Interact with deployed contract
        run: |
          if [[ "$CONTRACT_TYPE" == "ERC20" ]]; then
            echo "Debug: Interacting with ERC20 contract"
            npx hardhat run scripts/interact.js --network TESTNET
          elif [[ "$CONTRACT_TYPE" == "ERC721" ]]; then
            echo "Debug: Interacting with ERC721 contract"
            npx hardhat run scripts/interact-nft.js --network TESTNET
          elif [[ "$CONTRACT_TYPE" == "ERC1155" ]]; then
            echo "Debug: Interacting with ERC1155 contract"
            npx hardhat run scripts/interact-erc1155.js --network TESTNET
          else
            echo "Invalid CONTRACT_TYPE: $CONTRACT_TYPE"
            exit 1
          fi
        env:
          CONTRACT_TYPE: ${{ env.CONTRACT_TYPE }}
