name: Automated Contract Deployment and Interaction

on:
  push:
    branches:
      - debug

jobs:
  deploy_and_interact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.2  # or your desired Node.js version

      - name: Load environment variables from .env
        run: |
          cp .env .env.local
          echo "::add-mask::$(< .env.local)"
        shell: bash

      - name: Debug - List files in the directory
        run: |
          ls -al
        working-directory: ${{ github.workspace }}

      - name: Debug - Print contents of .env.local
        run: |
          cat .env.local
        working-directory: ${{ github.workspace }}

      - name: Debug - Print value of CONTRACT_TYPE
        run: |
          echo "CONTRACT_TYPE=$CONTRACT_TYPE"
        env:
          CONTRACT_TYPE: ${{ env.local.CONTRACT_TYPE }}

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Debug - Check the contract type
        run: |
          echo "Debug: CONTRACT_TYPE=$CONTRACT_TYPE"
        env:
          CONTRACT_TYPE: ${{ env.CONTRACT_TYPE }}

      - name: Deploy contract
        id: deployment
        run: |
          if [[ "$CONTRACT_TYPE" == "ERC20" ]]; then
            echo "Debug: Deploying ERC20 contract"
            npx hardhat run scripts/deploy.js --network TESTNET
          elif [[ "$CONTRACT_TYPE" == "ERC721" ]]; then
            echo "Debug: Deploying ERC721 contract"
            npx hardhat run scripts/deploy-nft.js --network TESTNET
          elif [[ "$CONTRACT_TYPE" == "ERC1155" ]]; then
            echo "Debug: Deploying ERC1155 contract"
            npx hardhat run scripts/deploy-erc1155.js --network TESTNET
          fi
        env:
          CONTRACT_TYPE: ${{ env.CONTRACT_TYPE }}

      - name: Store deployed contract address
        run: |
          NEW_CONTRACT_ADDRESS=$(cat contract-info.json | jq -r '.address')
          echo "CONTRACT_ADDRESS=$NEW_CONTRACT_ADDRESS" >> .env.local
          echo "::add-mask::CONTRACT_ADDRESS=$NEW_CONTRACT_ADDRESS"
        shell: bash
        working-directory: ${{ github.workspace }}

      - name: Debug - Print CONTRACT_ADDRESS
        run: |
          cat .env.local
        working-directory: ${{ github.workspace }}

      - name: Interact with deployed contract
        run: |
          if [[ "$CONTRACT_TYPE" == "ERC20" ]]; then
            echo "Debug: Interacting with ERC20 contract"
            npx hardhat run scripts/interact.js --network TESTNET
          elif [[ "$CONTRACT_TYPE" == "ERC721" ]]; then
            echo "Debug: Interacting with ERC721 contract"
            npx hardhat run scripts/interact-nft.js --network TESTNET
          elif [[ "$CONTRACT_TYPE" == "ERC1155" ]]; then
            echo "Debug: Interacting with ERC1155 contract"
            npx hardhat run scripts/interact-erc1155.js --network TESTNET
          fi
        env:
          CONTRACT_TYPE: ${{ env.CONTRACT_TYPE }}
