name: Smart Contract Testing

on:
  push:
    branches:
      - debug

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.14.2

    - name: Install dependencies
      run: npm install

    - name: Compile and deploy contracts
      run: |
        npx hardhat compile
        npx hardhat run scripts/deploy.js --network TESTNET

    - name: Capture contract address
      id: capture-contract-address
      run: |
        contract_address=$(cat contract-address.txt)
        echo "CONTRACT_ADDRESS=$contract_address" >> $GITHUB_ENV

    - name: Interact with contracts
      run: |
        npx hardhat run scripts/interact.js --network TESTNET
