name: Set GitHub Environment Variables from .env

on:
  push:
    branches:
      - debug

jobs:
  set_github_env:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load environment variables from .env
        run: |
          cp .env .env.local
          echo "::add-mask::$(< .env.local)"
        shell: bash

      - name: Read and set environment variables
        run: |
          while IFS= read -r line; do
            # Export each line from .env.local as a GitHub environment variable
            export $line
          done < .env.local
        shell: bash

      - name: Show GitHub environment variables
        run: env
