name: Automated Contract Deployment and Interaction

on:
  workflow_dispatch

jobs:
  deploy_and_interact_erc20:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.2

      - name: Load environment variables from .env
        run: |
          cp .env .env.local
          echo "::add-mask::$(< .env.local)"
        shell: bash

      - name: Set CONTRACT_TYPE
        run: |
          export CONTRACT_TYPE="ERC20"
        shell: bash

      - name: Debug - CONTRACT_TYPE
        run: |
          echo "Debug: CONTRACT_TYPE=$CONTRACT_TYPE"
        env:
          CONTRACT_TYPE: ${{ env.CONTRACT_TYPE }}

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Debug - Compile result
        run: ls -al

      - name: Deploy ERC20 contract
        id: deployment_erc20
        run: npx hardhat run scripts/deploy.js --network TESTNET
        env:
          CONTRACT_TYPE: ${{ env.CONTRACT_TYPE }}

      - name: Debug - Deploy result
        run: ls -al

      - name: Store deployed ERC20 contract address
        run: |
            NEW_CONTRACT_ADDRESS=$(cat contract-info.json | jq -r '.address')
            echo "CONTRACT_ADDRESS=$NEW_CONTRACT_ADDRESS" >> .env.local
            echo "::add-mask::CONTRACT_ADDRESS=$NEW_CONTRACT_ADDRESS"
        shell: bash

      - name: Debug - Contract Address
        run: cat .env.local