name: Automated Contract Deployment and Interaction

on:
  push:
    branches:
      - debug

jobs:
  deploy_and_interact_erc20:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.2

      - name: Load environment variables from .env
        run: |
          cp .env .env.local
          echo "::add-mask::$(< .env.local)"
        shell: bash

      - name: Set CONTRACT_TYPE
        run: |
          export CONTRACT_TYPE="ERC20"
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Deploy ERC20 contract
        id: deployment_erc20
        run: npx hardhat run scripts/deploy.js --network TESTNET
        env:
          CONTRACT_TYPE: ${{ env.CONTRACT_TYPE }}

      - name: Update .env CONTRACT_ADDRESS from contract-info.json
        run: |
          NEW_CONTRACT_ADDRESS=$(cat contract-info.json | jq -r '.address')
          node update-env.js $NEW_CONTRACT_ADDRESS
        shell: bash

      - name: Interact with deployed ERC20 contract
        run: npx hardhat run scripts/interact.js --network TESTNET
        env:
          CONTRACT_TYPE: ${{ env.CONTRACT_TYPE }}
