name: Automated Contract Deployment and Interaction

on:
  push:
    branches:
      - master

jobs:
  deploy_and_interact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.14.2  # or your desired Node.js version

      - name: Load environment variables from .env
        run: |
          cp .env .env.local
          echo "::add-mask::$(< .env.local)"
        shell: bash

      - name: Install dependencies
        run: npm install

      - name: Compile contracts
        run: npx hardhat compile

      - name: Deploy contract
        id: deployment
        run: |
          if [[ "$ENV" == "ERC20" ]]; then
            npx hardhat run scripts/deploy.js --network TESTNET
          elif [[ "$ENV" == "ERC721" ]]; then
            npx hardhat run scripts/deploy-nft.js --network TESTNET
          elif [[ "$ENV" == "ERC1155" ]]; then
            npx hardhat run scripts/deploy-erc1155.js --network TESTNET
          fi
        env:
          ENV: ${{ env.CONTRACT_TYPE }}

      - name: Store deployed contract address
        run: |
          NEW_CONTRACT_ADDRESS=$(cat contract-info.json | jq -r '.address')
          echo "CONTRACT_ADDRESS=$NEW_CONTRACT_ADDRESS" >> .env.local
          echo "::add-mask::CONTRACT_ADDRESS=$NEW_CONTRACT_ADDRESS"
        shell: bash
        working-directory: ${{ github.workspace }}

      - name: Interact with deployed contract
        run: |
          if [[ "$ENV" == "ERC20" ]]; then
            npx hardhat run scripts/interact.js --network TESTNET
          elif [[ "$ENV" == "ERC721" ]]; then
            npx hardhat run scripts/interact-nft.js --network TESTNET
          elif [[ "$ENV" == "ERC1155" ]]; then
            npx hardhat run scripts/interact-erc1155.js --network TESTNET
          fi
        env:
          ENV: ${{ env.CONTRACT_TYPE }}
