name: Automated Contract Deployment and Interaction

on:
  workflow_dispatch

jobs:
  deploy_erc20:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.14.2

    - name: Install dependencies
      run: npm install

    - name: Compile and deploy ERC20 contract
      run: |
        npx hardhat compile
        npx hardhat run scripts/deploy-erc20.js --network TESTNET

    - name: Capture ERC20 contract address
      id: capture-erc20-address
      run: |
        contract_address=$(cat contract-address.txt)
        echo "CONTRACT_ADDRESS=$contract_address" >> $GITHUB_ENV

    - name: Interact with ERC20 contract
      run: |
        npx hardhat run scripts/interact-erc20.js --network TESTNET

  deploy_erc721:
    runs-on: ubuntu-latest
    needs: deploy_erc20
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.14.2

    - name: Install dependencies
      run: npm install

    - name: Compile and deploy ERC721 contract
      run: |
        npx hardhat compile
        npx hardhat run scripts/deploy-erc721.js --network TESTNET

    - name: Capture ERC721 contract address
      id: capture-erc721-address
      run: |
        contract_address=$(cat erc721-contract-address.txt)
        echo "CONTRACT_ADDRESS=$contract_address" >> $GITHUB_ENV

    - name: Interact with ERC721 contract
      run: |
        npx hardhat run scripts/interact-erc721.js --network TESTNET

  deploy_erc1155:
    runs-on: ubuntu-latest
    needs: deploy_erc721
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18.14.2

    - name: Install dependencies
      run: npm install

    - name: Compile and deploy ERC1155 contract
      run: |
        npx hardhat compile
        npx hardhat run scripts/deploy-erc1155-new.js --network TESTNET

    - name: Capture ERC1155 contract address
      id: capture-erc1155-address
      run: |
        contract_address=$(cat erc1155-contract-address.txt)
        echo "CONTRACT_ADDRESS=$contract_address" >> $GITHUB_ENV

    - name: Interact with ERC1155 contract
      run: |
        npx hardhat run scripts/interact-erc1155-new.js --network TESTNET
